# Generated by Django 5.0.2 on 2024-07-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('npass', models.CharField(max_length=30)),
                ('cpass', models.CharField(max_length=30)),
            ],
        ),
    ]
