# Generated by Django 5.0.2 on 2024-09-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiAPI', '0002_remove_customers_cpass_customers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('currentloc', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('emails', models.CharField(max_length=30)),
                ('modile', models.IntegerField(default='0')),
                ('addinfo', models.CharField(max_length=300)),
            ],
        ),
    ]
