# Generated by Django 5.0.2 on 2024-09-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiAPI', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='modile',
            new_name='mobile',
        ),
    ]
