# Generated by Django 5.0.2 on 2024-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiAPI', '0004_rename_modile_booking_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
